name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

# Add permissions for the workflow
permissions:
  contents: write
  packages: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build web version
      run: npm run build-web
    
    - name: Check build output
      run: ls -la dist/
    
    # Build without automatic publishing
    - name: Build Linux packages
      run: npm run build-electron
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: List built files
      run: ls -la electron-dist/
    
    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-appimage
        path: electron-dist/*.AppImage
    
    - name: Upload DEB artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-deb
        path: electron-dist/*.deb
    
    - name: Upload RPM artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-rpm
        path: electron-dist/*.rpm

  release:
    needs: build-linux
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          linux-appimage/*.AppImage
          linux-deb/*.deb
          linux-rpm/*.rpm
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 